#!/usr/bin/env python3
"""
Demo: System Commands with SmartSwitch

This demonstrates:
1. System commands (_system handler) auto-published by Publisher
2. Help auto-generated from SmartSwitch (NO manual code!)
3. CLI channel showing system commands
4. All using ONLY SmartSwitch APIs
"""

import sys
from pathlib import Path

# Add src_new to path
sys.path.insert(0, str(Path(__file__).parent))

from example_app import ShopApp
from channels.cli import PublisherCLI


def demo_system_commands():
    """Demo system commands."""
    print("=" * 70)
    print("DEMO: System Commands (Auto-generated by SmartSwitch)")
    print("=" * 70)
    print()

    # Create app
    print("1. Creating ShopApp...")
    app = ShopApp()
    print(f"   ✓ Publisher created: {app.__class__.__name__}")
    print(f"   ✓ Handlers published: {list(app.published_instances.keys())}")
    print()

    # Create CLI
    print("2. Creating CLI channel...")
    cli = PublisherCLI(app)
    print("   ✓ CLI channel ready")
    print()

    # Show system commands help
    print("3. System Commands Help (auto-generated from SmartSwitch):")
    print("-" * 70)
    print("   $ smpub run myapp _system")
    print()
    cli.run(["_system"])
    print()

    # List handlers
    print("4. List Handlers:")
    print("-" * 70)
    print("   $ smpub run myapp _system list_handlers")
    print()
    cli.run(["_system", "list_handlers"])
    print()

    # Get handler info
    print("5. Get Handler Info:")
    print("-" * 70)
    print("   $ smpub run myapp _system get_handler_info shop")
    print()
    # Note: This would need arg parsing, for now show concept
    print("   (Would show shop handler details)")
    print()

    # Get API tree
    print("6. Get Complete API Tree:")
    print("-" * 70)
    print("   $ smpub run myapp _system get_api_tree")
    print()
    cli.run(["_system", "get_api_tree"])
    print()


def demo_general_help():
    """Demo general help."""
    print("=" * 70)
    print("DEMO: General Help (Auto-generated from SmartSwitch)")
    print("=" * 70)
    print()

    app = ShopApp()
    cli = PublisherCLI(app)

    print("1. Show all handlers:")
    print("-" * 70)
    print("   $ smpub run myapp --help")
    print()
    cli.run(["--help"])
    print()

    print("2. Show specific handler (shop):")
    print("-" * 70)
    print("   $ smpub run myapp shop")
    print()
    cli.run(["shop"])
    print()


def demo_smartswitch_introspection():
    """Demo SmartSwitch introspection."""
    print("=" * 70)
    print("DEMO: SmartSwitch Introspection (Single Source of Truth)")
    print("=" * 70)
    print()

    app = ShopApp()

    print("1. SmartSwitch provides complete API schema:")
    print("-" * 70)

    # Get schema from SmartSwitch - NO custom code!
    schema = app.api.describe()

    print(f"   Root API: {schema.get('name')}")
    print(f"   Children: {list(schema.get('children', {}).keys())}")
    print()

    print("2. Each handler has its own schema:")
    print("-" * 70)

    shop_instance = app.published_instances["shop"]
    shop_schema = shop_instance.__class__.api.describe()

    print("   Handler: shop")
    print(f"   Methods: {list(shop_schema.get('methods', {}).keys())}")
    print()

    print("3. System handler schema:")
    print("-" * 70)

    system_instance = app.published_instances["_system"]
    system_schema = system_instance.__class__.api.describe()

    print("   Handler: _system")
    print(f"   Methods: {list(system_schema.get('methods', {}).keys())}")
    print()

    print("4. ALL from SmartSwitch - NO manual code!")
    print("-" * 70)
    print(
        """
   ✓ Help = switcher.describe()
   ✓ Method list = switcher.entries()
   ✓ Execution = switcher.get(method)
   ✓ Validation = built-in SmartSwitch
   ✓ NO inspect, NO custom parsing, NO duplication
    """
    )


def main():
    """Run all demos."""
    print("\n" + "=" * 70)
    print("SmartPublisher - System Commands Demo")
    print("=" * 70)
    print()

    try:
        demo_system_commands()
        print("\n")
        demo_general_help()
        print("\n")
        demo_smartswitch_introspection()

        print("\n" + "=" * 70)
        print("Key Takeaways")
        print("=" * 70)
        print(
            """
1. System commands (_system) auto-published by Publisher
2. Help is auto-generated from SmartSwitch.describe()
3. NO custom code - SmartSwitch does EVERYTHING:
   - Introspection (describe)
   - Validation (automatic)
   - Execution (get + call)
4. Single source of truth: Switcher
5. Works same way on ALL channels (CLI, HTTP, etc.)

Try these commands:
  $ smpub run myapp --help
  $ smpub run myapp _system
  $ smpub run myapp _system list_handlers
  $ smpub run myapp shop
  $ smpub run myapp shop list
        """
        )

    except Exception as e:
        print(f"\n❌ Error: {e}")
        import traceback

        traceback.print_exc()


if __name__ == "__main__":
    main()
